/* empty css                      */import{S as m,i as a}from"./assets/vendor-BbWXjE2X.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const h="46807099-cbb80e6feaa2f2d0498acb57e",p="https://pixabay.com/api/";function g(n){const o=`${p}?key=${h}&q=${encodeURIComponent(n)}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(o).then(r=>{if(!r.ok)throw new Error("Error fetching data");return r.json()}).then(r=>r.hits).catch(r=>{throw console.error("Error fetching images:",r),r})}const l=document.querySelector(".gallery");function y(){l.innerHTML=""}function b(n){const o=n.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:s,comments:f,downloads:d})=>`
        <a href="${i}" class="gallery__item">
            <img class="gallery-link" src="${r}" alt="${e}" loading="lazy" />
            <div class="info">
                <p class="text-item"><b>Likes:</b> ${t}</p>
                <p class="text-item"><b>Views:</b> ${s}</p>
                <p class="text-item"><b>Comments:</b> ${f}</p>
                <p class="text-item"><b>Downloads:</b> ${d}</p>
            </div>
        </a>
    `).join("");l.insertAdjacentHTML("beforeend",o),new m(".gallery a").refresh()}const L=document.querySelector("#search-form"),u=document.querySelector(".loader");function w(){u.classList.remove("hidden")}function c(){u.classList.add("hidden")}L.addEventListener("submit",n=>{n.preventDefault();const o=n.currentTarget.elements.query.value.trim();if(!o){a.error({title:"Error",message:"Please enter a search term!"});return}y(),w(),g(o).then(r=>{c(),r.length===0?a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):b(r)}).catch(r=>{c(),a.error({title:"Error",message:"Something went wrong. Please try again later!"})})});
//# sourceMappingURL=index.js.map
